### ISSUE TITLE
Sample rate issue on MacOS?

### ISSUE THREAD

**Issue by Osmose** [sasq64/musicplayer#1]
Yo! First off, this library is amazing. I've been working on an electron-based music player that manually did a similar thing as this library already does. I replaced my work with this library and it works better on all fronts. Thank you for writing it!

One thing I'm hitting on MacOS is that when I'm using an audio device with a sample rate set at 48kHz, things work fine, but at 44.1kHz (my headphones _only_ support this sample rate), I notice two issues:

1. PS2 sound files are pitched incorrectly due to a sample rate mismatch.
2. Certain PS1 sound files (like Xenogears - 214 Pray for the People's Joy) seem to cause a crash when loaded.

I'm pretty inexperienced at C/C++ and haven't been able to diagnose the issue. Do you have any ideas or tips on how to handle this? The first problem I could handle by detecting the current audio device and resampling myself, but the second problem is a bit harder to deal with.

**Comment by Osmose** [comment]
For slightly more context, the way I'm playing this stuff back is through a C wrapper that wraps the logic for creating `ChipPlayer` instances and calling `getSamples` on them. I need to use a C wrapper because the UI is written in JavaScript (because it's electron) and node-ffi only really knows how to call C functions.

Once I have an array of sample data in JavaScript I'm just feeding it directly to the Web Audio API, and the browser takes over the rest of the output logic.

I'm not sure if that's helpful context, but maybe!

**Comment by sasq64** [comment]
Sorry for not not answering earlier, forgot about this...
Anyway, it's weird; My player system basically assumes all plugins will produce 44100Hz audio and resample it internally if the underlying player doesn't produce this frequency.

So if you check the [USFPlugin.cpp](plugins/usfplugin/USFPlugin.cpp) for instance, I use libresampler to resample the audio because of this reason... so if you're playing at 48KHz you're side must be doing some resampling or the audio is pitched/speed up.
